imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }


easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
            edit:
              fields: ['id', 'username', 'email', 'plainPassword']
        Subscription:
            class: AppBundle\Entity\Subscription
        LanPosition:
            class: AppBundle\Entity\LanPosition

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    app.path.product_images: /uploads/images/products
    app.path.user_contracts: /uploads/files/user/contracts

framework:
    #esi:             ~
    translator:      { fallbacks: [%locale%] }
    secret:          %secret%
    router:
        resource: %kernel.root_dir%/config/routing.yml
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Doctrine Configuration
doctrine:
    dbal:
        url: %database_url%
        charset:  UTF8
        server_version: 5.6
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# File Uploader
vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: %app.path.product_images%
            upload_destination: %kernel.root_dir%/../web/uploads/images/products
        user_contracts:
            uri_prefix: %app.path.user_contracts%
            upload_destination: %kernel.root_dir%/../web/uploads/files/user/contracts

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    resetting:
      retry_ttl: 0
    from_email:
        address:        "lan@palenciakernelpanic.net"
        sender_name:    "PKP Lan"

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

hwi_oauth:
    connect:
        account_connector: my.oauth_aware.user_provider.service
    firewall_names: [main]
    fosub:
      username_iterations: 30
      properties:
          facebook:    facebook_id
          google: google_id
    resource_owners:
      google:
          type:                google
          client_id:           "%google_client_id%"
          client_secret:       "%google_secret%"
          scope:               "email profile"
      facebook:
          type:                facebook
          client_id:           "%facebook_client_id%"
          client_secret:       "%facebook_secret%"
          scope:               "email public_profile"
          options:
                display: popup #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions